- .github/workflows/maven-verify-with-its-test.yml
- .gitignore
- README.md
- pom.xml
Test workflow will only trigger on push event, I'm looking how to dynamically reference shared workflows ....
https://github.community/t/self-reference-a-shared-workflow-call-for-testing/206905
> Testing workflows

- README.md
> Complete example of usage

- .github/workflows/maven-verify-test.yml
- .github/workflows/maven-verify.yml
Some project need be executed with different goals
so provide possibility to override it
> Goals for build step in inputs

- .github/workflows/maven-verify.yml
Some project require specific Maven version
so let's allow changing default version
> Use Maven wrapper to set up Maven version for build

- .github/workflows/maven-verify.yml
Added `timeout-minutes`, `ff-timeout-minutes` and `max-parallel`.
This can be an update in V2 or a new V3.
> timeout-minutes, ff-timeout-minutes and max-parallel

- .github/workflows/maven-verify.yml
- pom.xml
- src/main/java/org/apache/test/TestApp.java
- build site only in ff
- upload site as GH artifact
- parent pom 35
- example java code
> Site build improvement

- .github/workflows/maven-verify.yml
Improvement for multi module projects
> Stage site output

- .github/workflows/maven-verify.yml
Add more flags:
* to control is FF step needed at all
* to control is FF required to build site at all
> Add more FF flags

- .github/workflows/maven-verify-test.yml
We can use special reference to action in local workspace. 
So we will test the same code what is currently changed.
> Use local reference action during test

- .github/workflows/maven-verify.yml
cherry-pick of https://github.com/apache/maven-gh-actions-shared/commit/6fb412f2817e5c91dd530405f4568204e4fbea6e
> add a clean to ensure we do not lock files for a windows build

- .github/workflows/maven-verify.yml
same as we have for https://github.com/codehaus-plexus/.github
> Add option to include ad-hoc jdks to testing matrix

- .github/workflows/maven-verify.yml
- .github/workflows/release-drafter.yml
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs 
https://github.com/release-drafter/release-drafter
> Restrict permissions to GITHUB_TOKEN

- .github/workflows/maven-verify.yml
temurin doesn't support JDK 8 on macOS 14
> Switch JDK distribution to zulu as default

- .github/workflows/maven-verify.yml
Required for Maven Wagon tests
https://github.com/apache/maven-wagon/tree/master
https://github.com/actions/runner-images/issues/10636
> Install Subversion client on Linux runners

- README.md
There is no type demilestoned for pull_request_target
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target
> PR Automation - next fix in docs

- .github/workflows/release-drafter.yml
needed for multi-branch releases
> Allow to pass config-name for release-drafter

- .github/workflows/pr-automation.yml
There are projects that we have multiple branches under maintenance
> PR Automation allow assign milestone to branch

- .github/labels.js
Name, description and color from jira for easy mapping.
After it we should update list at: https://maven.apache.org/developers/conventions/github.html
> Add priority labels

- .github/workflows/pr-automation.yml
> Fix NPE when milestone doesn't have a description

- .github/workflows/maven-verify.yml
In other case we execute this job twice on each PR.
> Check event which trigger build on setup job

- .github/workflows/pr-automation.yml
As we use only close event
we not need a job for checking review decision
> Simplify PR Automation

- .github/workflows/pr-automation.yml
We assign issue to person who close it ... so we can do the same with PR
> Assign PR to person who merge it

- .github/release-drafter.yml
- put the deprecated items more upper
- put the dependencies updates at the end
> Reorder items in release drafter template

- .github/workflows/stale.yml
We can also remove the Stale label
> Remove Stale label on comments

- .github/workflows/release-drafter.yml
workaround for issue:
- https://github.com/release-drafter/release-drafter/issues/1450
> Verify status of release-drafter execution
